name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: buildstep1
        uses: actions/checkout@v4
      - name: buildstep2
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
